name: Manual Release Build

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show release version
        run: echo "Building release version ${{ github.event.inputs.release }}"
